### ISSUE TITLE
Social Cards

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alv-website#129]
Bilde, tittel, osv når en deler en blog på Facebook, Twitter og LinkedIn.

**Comment by TheKnarf** [comment]
Tester for twitter:
https://cards-dev.twitter.com/validator?

Facebook:
https://developers.facebook.com/tools/debug/

LinkedIn:
https://www.linkedin.com/post-inspector/

**Comment by TheKnarf** [comment]
Look into setting up:
https://www.sanity.io/plugins/social-preview

**Comment by TheKnarf** [comment]
While most of this is fixed I'll reopen it so that we remember to look into the sanity plugin.

**Comment by mikkelcodes** [comment]
Closed as social share functionality is now implemented. Sanity social preview now has its own separate issue. #330
