### ISSUE TITLE
Webm-videoes on Employee-page

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alv-website#133]
1. File upload on Sanity
2. Gatsby pulls these down as a part of the build
3. We load them when you click on an employee

**Comment by mikkelcodes** [comment]
Mux ser ut til å være den eneste gode, eksisterende integrasjoner for å gjøre dette.

https://www.sanity.io/mux
"Mention mux to @knut in the slack and he'll get you sorted." - Sanity har visst et samarbeid med mux slik at det vil være noen ekstra fordeler ved å gå får mux.

Front-end kode for dette er på plass, back-end kode for mux file-upload er også på plass, men kommentert ut. Eneste som trengs for å komme i gang med dette, er at dere lager en bruker og laster opp video-filer navngitt etter ansattes navn, gjerne med bindestrek mellom navnene. 

Nåværende løsning som er "aktiv" er video-embed basert på video-url-feltet til ansatte i sanity studio.
