### ISSUE TITLE
Horizontal sidebar and white gap

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#136]
![image](https://user-images.githubusercontent.com/73942505/104182968-8ce61c00-5411-11eb-9032-8411e0cb3cc6.png)

See attached image

**Comment by mikkelcodes** [comment]
What page is this?

**Comment by professoralv** [comment]
> What page is this?

Front page

**Comment by professoralv** [comment]
> What page is this?

But the gap is even bigger on i.e. http://dev.alv.no/c-utvikler
I'm on a 14" screen

**Comment by mikkelcodes** [comment]
done
