### ISSUE TITLE
Change contact details on contact us page

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#159]
![image](https://user-images.githubusercontent.com/73942505/105745618-c3a65100-5f3e-11eb-9166-73138acf310d.png)
Address should be Pløensgate 1
![image](https://user-images.githubusercontent.com/73942505/105745699-db7dd500-5f3e-11eb-9ead-a2aec573754f.png)
telephone number should be 915 30 363

**Comment by TheKnarf** [comment]
This must also be done for google maps.
