### ISSUE TITLE
Error when viewing employee videos on mobile

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#160]
![image](https://user-images.githubusercontent.com/73942505/105811865-8a58fa00-5fad-11eb-87f4-72cea1187dc1.png)

**Comment by TheKnarf** [comment]
The bug is only on iPhone

**Comment by mikkelcodes** [comment]
<img width="1116" alt="Screenshot 2021-01-28 at 07 45 41" src="https://user-images.githubusercontent.com/61052733/106101061-a9869180-613d-11eb-8f44-e5e9cef9c3f4.png">

Har forsøkt å finne en løsning på dette, men det ser ut til at Safari og iOS per dags dato ikke støtter webm (et format utviklet av Google).

Alternativene våre er da MP4-format eller eventuelt videostreaming fra YT, Vimeo eller Mux.

**Comment by mikkelcodes** [comment]
Et forslag til en midlertidig løsning for ansatte-videoer kan være å streame disse fra youtube ettersom mange/alle videoene ligger der allerede. Det kan jeg ordne i koden og ingen endringer i sanity dataen er nødvendige for å implementere denne midlertidige løsningen i så fall.

**Comment by mikkelcodes** [comment]
Dersom det blir aktuelt, kan cloudconvert.com kan brukes for å "masse-konvertere" WebM filene til MP4.

**Comment by TheKnarf** [comment]
Hm, I was not aware that WebM support was so bad in Safari. I guess we need to discuss what we do about it.

**Comment by TheKnarf** [comment]
An `<video>` element can support multiple formats: https://stackoverflow.com/questions/22698718/can-a-html-5-video-tag-have-multiple-mp4-sources-with-different-codecs

Thereby letting the browser pick the one that works for them.

**Comment by mikkelcodes** [comment]
I guess that means we'll have two video upload fields in Sanity per employee, one for WebM and another for Mp4? Or did you have in mind some kind of automated file format conversion workflow?

**Comment by TheKnarf** [comment]
Yes, if we don't decide to go for Vimeo or Mux, then having two fields would be the solution. We could always make an automated video transcoder, but that's really on the bottom of the backlog as far as priorities goes.

I suggest that we discuss with @professoralv and Jakob what solution they would prefer for the employee page. For the frontpage I would like two fields.

**Comment by TheKnarf** [comment]
I split this issue into two other issues:

- #173
- #174
