### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alv-website#17]
- Sanity field in settings
- Add google analytics to gatsby

**Comment by professoralv** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145784500-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-145784500-1');
</script>
