### ISSUE TITLE
Black bar on top and bottom of videos

### ISSUE THREAD

**Issue by TheKnarf** [Alv-no/alv-website#177]
![Screenshot 2021-01-28 at 13 42 40](https://user-images.githubusercontent.com/213777/106140195-bb345d00-616e-11eb-989a-086289d4a707.png)

**Comment by TheKnarf** [comment]
![Screenshot 2021-09-07 at 10 16 53](https://user-images.githubusercontent.com/213777/132309944-c829493d-a2e8-40b8-bc3e-088592df3216.png)

A bit random if it looks right or not

**Comment by mikkelcodes** [comment]
Keep black bars. Make sure they show on all videos
