### ISSUE TITLE
Finish blog filter module

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#200]
This module is not working 
![image](https://user-images.githubusercontent.com/73942505/106728645-f3271e80-660c-11eb-895f-e97b88932847.png)

**Comment by TheKnarf** [comment]
Since we have previously seen some differences between the `dev` and `build` command from `gatsby`, try to test it in both @mikkelcodes. Especially for this issue. Writing Jest unit tests or Cypress component tests may also help here to ensure that the code work correctly.

**Comment by TheKnarf** [comment]
Filter should work like this:

- If you select multiple categories and authors, then you should show all articles that share at least one category and at least one author.

**Comment by TheKnarf** [comment]
When you click away from it it should close the menu.
