### ISSUE TITLE
Create related blog posts module

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#201]
It's missing from the picture below.
![image](https://user-images.githubusercontent.com/73942505/106729016-5a44d300-660d-11eb-9dee-f5c637c41f5d.png)

It should be like this
![image](https://user-images.githubusercontent.com/73942505/106729145-7fd1dc80-660d-11eb-88ed-a1dc14e17b25.png)

**Comment by TheKnarf** [comment]
Duplicate issue: #334
