### ISSUE TITLE
Vi Tilbyr and all sub pages 

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#203]
Make it possible to publish `vi tilbyr`-pages from the sanity cms.

**Comment by TheKnarf** [comment]
![Screenshot 2021-02-04 at 12 11 37](https://user-images.githubusercontent.com/213777/106884871-27204380-66e2-11eb-8299-fb61f3858377.png)

**Comment by TheKnarf** [comment]
https://xd.adobe.com/view/da334a1f-ae93-40c9-a27d-0c6b4307012f-8f60/screen/3bb9a558-6a0a-4019-a14d-b1b2d5521a2d

**Comment by TheKnarf** [comment]
In Sanity we'll need ti schemas:

- Categories (Systemutivkling, Projsketledelse, digitalisering, etc)
- Pages (.net utvikler, java utvikler, etc)

**Comment by TheKnarf** [comment]
![Screenshot 2021-02-04 at 12 47 10](https://user-images.githubusercontent.com/213777/106888616-1d4d0f00-66e7-11eb-8252-02559c5e65c6.png)

Note the breadcrumb for the page.

`Home / Vi Tilbyr / Category name / Page Name`
