### ISSUE TITLE
Employee filter logic bug

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#207]
This is how it is supposed to look like when first loading the page: 
![image](https://user-images.githubusercontent.com/73942505/106762079-c3404100-6635-11eb-87ae-4d77234b4809.png)
No tag is selected, and by default it shows all employees. If a tag is selected, it will only show employees that fit the selected tags.

**Comment by professoralv** [comment]
Currently all tags are selected by default when loading the page. But it should work in accordance with the previous comment.

**Comment by mikkelcodes** [comment]
fixed in pr #300
