### ISSUE TITLE
Create sitemap.xml

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#248]
Create a dynamic sitemap.xml file that we can submit to google search console

**Comment by TheKnarf** [comment]
Not sure why this is an issue, seems like it's been there all along.

**Comment by TheKnarf** [comment]
Nevermind, it's there, but the webserver returns the wrong mime type.

https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=alv.no&submit=Validate+Sitemap

I'll fix it.
