### ISSUE TITLE
Can't close Hamburger Menu on mobile

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#253]
Clicking on X to close the hamburger menu doesn't work (most of the time) on mobile.

**Comment by rudgutter** [comment]
Can't reproduce. Tested locally in Chrome when running dev server and tested in production with Brave(Chromium) and Safari on iOS 14.4.

I reported the original issue to @professoralv, but this might have been a glitch or an occurrence of fat fingers. Will close for now, but we can reopen this if it resurfaces.
