### ISSUE TITLE
Remove "Digitalisering" from website

### ISSUE THREAD

**Issue by jakobhg** [Alv-no/alv-website#278]
We have decided to remove "Digitalisering" from both category pages and "Vi Tilbyr".

<img width="1409" alt="Skjermbilde 2021-03-21 kl  15 31 07" src="https://user-images.githubusercontent.com/79189450/111908762-be571580-8a5a-11eb-9d9b-dc61aadb8f0d.png">
<img width="1429" alt="Skjermbilde 2021-03-21 kl  15 31 30" src="https://user-images.githubusercontent.com/79189450/111908763-c0b96f80-8a5a-11eb-9db8-37f94f8ee3a4.png">

**Comment by TheKnarf** [comment]
- Jakob: `Digitalisering` cataegory page can be removed in Sanity
- Mikkel: Make `Vi tilbyr`-siden changable. (You may allready have another issue for this).

**Comment by jakobhg** [comment]
I'm not allowed to delete "Digitalisering" from Sanity. 
<img width="715" alt="Skjermbilde 2021-03-23 kl  14 15 19" src="https://user-images.githubusercontent.com/79189450/112152162-4582c580-8be2-11eb-8341-49c54f7c9af5.png">

**Comment by TheKnarf** [comment]
@mikkelcodes can you assist @jakobhg on his problem?

**Comment by mikkelcodes** [comment]
I explained in Slack the process and also solved this specific case in sanity. If you click on the details button on the screenshot above, it will tell that the Our Services Page is referring to the current page you are trying to delete. So, the reference must be changed first before deletion: From slack:

Ordnet det fra Sanity: På vi-tilbyr siden endret jeg referansen fra digitalisering til data & analyse (ettersom digitalisering slettes), deretter slettet jeg digitalisering-dokumentet. Menyen har oppdatert seg og digitalisering-siden finnes ikke lenger (lokalt hos meg). Bygger vi dev på nytt nå, reflekteres dette (edited).

I thought we crossed this one off. @jakobhg, please let me know if there are any further questions on this one

**Comment by jakobhg** [comment]
This one is OK. But "Digitalisering" still show on homepage: 

Here we also have some dead links. 

<img width="1737" alt="Skjermbilde 2021-03-24 kl  17 08 53" src="https://user-images.githubusercontent.com/79189450/112343821-c796eb00-8cc3-11eb-904b-7154d5e34a14.png">
