### ISSUE TITLE
text remains hidden/faded on mobile

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#293]
Galaxy s20.
Text remains hidden/faded even when scrolling down.
![bug 2](https://user-images.githubusercontent.com/73942505/112729918-df25dc00-8f2e-11eb-958d-c5d957c0d2fc.jpg)
![bug](https://user-images.githubusercontent.com/73942505/112729923-e351f980-8f2e-11eb-8598-7ed9d5387212.jpg)

**Comment by mikkelcodes** [comment]
fade removed in a previous pr
