### ISSUE TITLE
scroll to continue not showing on mobile

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#294]
Samsung Galaxy S20 + 

![scroll to continue](https://user-images.githubusercontent.com/73942505/112730139-2bbde700-8f30-11eb-92c6-a5e759d5e8b0.jpg)

**Comment by mikkelcodes** [comment]
covered by another recently created issue

**Comment by TheKnarf** [comment]
@mikkelcodes Please post the issue number as a comment before closing the issue.

**Comment by mikkelcodes** [comment]
issue #312
