### ISSUE TITLE
Employees can't be removed

### ISSUE THREAD

**Issue by jakobhg** [Alv-no/alv-website#299]
Authors/ employees can't be removed from Sanity. When people quit we have to have the possibility to remove them from "ansatte" but continue to have their blogposts posted. 

<img width="488" alt="Skjermbilde 2021-04-06 kl  20 02 24" src="https://user-images.githubusercontent.com/79189450/113757760-46a01080-9713-11eb-97b7-5ff9758aef45.png">
<img width="490" alt="Skjermbilde 2021-04-06 kl  20 02 16" src="https://user-images.githubusercontent.com/79189450/113757764-4738a700-9713-11eb-9143-e75814473646.png">

**Comment by TheKnarf** [comment]
Will be fixed by #325
