### ISSUE TITLE
Responsiv bug

### ISSUE THREAD

**Issue by jakobhg** [Alv-no/alv-website#301]
Bug on responsiveness on "Jobbe i Alv" -> job posts

![Screenshot 2021-04-14 at 16 21 30](https://user-images.githubusercontent.com/213777/114726245-7ff10580-9d3d-11eb-82d7-a2ca488abeec.png)

**Comment by TheKnarf** [comment]
This happens if the height of the browser window is to small.

**Comment by mikkelcodes** [comment]
fixed in #317
