### ISSUE TITLE
missing sections from category pages

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#308]
![image](https://user-images.githubusercontent.com/73942505/114422064-3a560080-9bb6-11eb-8d86-2f8033df16a7.png)

**Comment by TheKnarf** [comment]
`Hva gjør vi`:
- optional om vi har lagt inn data.

`Vårt team`:
- Vårt team, plukk opp til fire stykk som har samme tag som kategorisiden.
- Om noen har ansinitet / år jobbet så sortert og vise de fire some har lengst erfaring
