### ISSUE TITLE
Create universal container component

### ISSUE THREAD

**Issue by mikkelklokkerud** [Alv-no/alv-website#519]
Note to self:
- A react component with set margins for all responsive sizes. 
- If background color is set, wrapper should use paddings
- If no bg color is set, wrapper should use margins (allowing them to collapse)

**Comment by rsletta** [comment]
@mikkelcodes, is this issue still active?

**Comment by klyngen** [comment]
This has been solved in the feature/landingpage feature. No need for a container-component, when you can do the following
`container max-w-1440` then flex that container if needed.
