### ISSUE TITLE
Feil språk på page tabs

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#703]
Page title tab står på norsk selvom jeg har på EN language. Fant ikke noe sted i Sanity å rette det.
![image](https://user-images.githubusercontent.com/73942505/170934545-2e37dbdc-5454-44f2-a1e1-0f93ca2c1f08.png)

- [x] Implement english titles
- [x] Make sure we also set correct metadata in layout-component

**Comment by klyngen** [comment]
- [ ] Implement english titles

**Comment by klyngen** [comment]
Estimate 2 hours
