### ISSUE TITLE
503 bad gateway button

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#732]
Den første read more knappen i hovedbanneren gir bad gateway feil.
Dere kan linke knappen til https://alv-biotech.com/collaborate-with-us/invest/
![image](https://user-images.githubusercontent.com/73942505/185049959-f0a92aef-944c-4ba8-8856-2cd94670687b.png)

*Klingen:*
Estimat 30 min

- Problemet kommer av at URL'en ikke er endret

**Comment by klyngen** [comment]
Link was not entered correctly in sanity-studio. Changed the link value. And it was obvious that we needed a proper 404-page and not an NGINX-error. Configured nginx so we get a 404-page
