### ISSUE TITLE
Page titles in english are displayed in norwegian

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#770]
This is at least true on the landing page, and it is confusing english google search results.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/73942505/196379496-b8540750-c073-459f-ab03-53ed8be80926.png">

**Comment by professoralv** [comment]
Correct page titles are already entered into Sanity.

**Comment by klyngen** [comment]
Duplicate of https://github.com/Alv-no/alv-website/issues/703
